### ISSUE TITLE
Error [INVALID_INTENTS]: Invalid intent provided for WebSocket intents.

### ISSUE THREAD

**Issue by aaronbesson** [boringcrypto/UnRealArtDiscordBot#3]
Hi,

Thanks for this, but i'm getting an error:
Error [INVALID_INTENTS]: Invalid intent provided for WebSocket intents.

Any idea what i may be doing wrong on the config side?

**Comment by boringcrypto** [comment]
This repo isn't to be used as is... but you're free to copy/paste/edit and make it do something useful for you... I didn't look into it, but it probably has the server hardcoded or you haven't provided username/pass or something like that. Or you have to approve something manually first...
